application:
  subdomain: kindly-rss
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://kindly-rss:3000/
services:
  kindly-rss:
    environment:
      - DATA_PATH=/home/data
    # upstream: nicoan/kindly-rss-reader:0.4.0
    image: docker.1ms.run/nicoan/kindly-rss-reader:0.4.0
    binds:
      - /lzcapp/var/data:/home/data
